# Generated by Django 4.2.4 on 2023-08-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Enter a book language (e.g. English)', max_length=100, verbose_name='Language'),
        ),
    ]
