# Generated by Django 4.2.4 on 2023-08-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('view_all_borrowed', 'View all borrowed books'), ('can_mark_returned', 'Can mark returned'))},
        ),
    ]
