# Generated by Django 4.2.4 on 2023-08-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('affect_authors', 'Can affect authors'),)},
        ),
    ]
