# Generated by Django 4.2.4 on 2023-08-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_affect_books', 'Can affect books'),)},
        ),
    ]
